package com.models;
// Generated Dec 6, 2017 5:39:32 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * CashTransaction generated by hbm2java
 */
public class CashTransaction implements java.io.Serializable {

	private Integer id;
	private CashAccount cashAccount;
	private Date date;
	private BigDecimal amount;
	private BigDecimal balance;
	private String description;

	public CashTransaction() {
	}

	public CashTransaction(CashAccount cashAccount, Date date, BigDecimal amount, BigDecimal balance,
			String description) {
		this.cashAccount = cashAccount;
		this.date = date;
		this.amount = amount;
		this.balance = balance;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CashAccount getCashAccount() {
		return this.cashAccount;
	}

	public void setCashAccount(CashAccount cashAccount) {
		this.cashAccount = cashAccount;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
