package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * CashTransaction generated by hbm2java
 */
public class CashTransaction implements java.io.Serializable {

	private Integer id;
	private CashAccount cashAccount;
	private Date date;
	private BigDecimal amount;
	private BigDecimal balance;
	private String description;
	
	private transient StringProperty accountName = new SimpleStringProperty();

	public CashTransaction() {
	}

	public CashTransaction(CashAccount cashAccount, Date date, BigDecimal amount, BigDecimal balance,
			String description) {
		this.cashAccount = cashAccount;
		this.date = date;
		this.amount = amount;
		this.balance = balance;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CashAccount getCashAccount() {
		return this.cashAccount;
	}

	public void setCashAccount(CashAccount cashAccount) {
		this.cashAccount = cashAccount;
		accountName.setValue(cashAccount.toString());
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	public StringProperty descriptionProperty() {
		StringProperty descProperty = new SimpleStringProperty();
		descProperty.setValue(description);
		return descProperty;
	}	
	public StringProperty amountProperty() {
		StringProperty amountProperty = new SimpleStringProperty();
		amountProperty.setValue(amount.toString());
		return amountProperty;
	}
	public IntegerProperty IdProperty() {
		IntegerProperty idProperty = new SimpleIntegerProperty();
		idProperty.setValue(id);
		return idProperty;
	}
	public StringProperty accountProperty() {
		return accountName;
	}

}
