package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CashAccount generated by hbm2java
 */
public class CashAccount implements java.io.Serializable {

	private Integer id;
	private Investor investor;
	private BigDecimal balance;
	private Set<CashTransaction> cashTransactions = new HashSet<CashTransaction>(0);

	public CashAccount() {
	}

	public CashAccount(Investor investor, BigDecimal balance) {
		this.investor = investor;
		this.balance = balance;
	}

	public CashAccount(Investor investor, BigDecimal balance, Set<CashTransaction> cashTransactions) {
		this.investor = investor;
		this.balance = balance;
		this.cashTransactions = cashTransactions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Investor getInvestor() {
		return this.investor;
	}

	public void setInvestor(Investor investor) {
		this.investor = investor;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public Set<CashTransaction> getCashTransactions() {
		return this.cashTransactions;
	}

	public void setCashTransactions(Set<CashTransaction> cashTransactions) {
		this.cashTransactions = cashTransactions;
	}

}
