package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private Portfolio portfolioByBuyerPortfolioId;
	private Portfolio portfolioBySellerPortfolioId;
	private Security security;
	private User user;
	private Date date;
	private int quantity;
	private BigDecimal price;
	private BigDecimal buyerBrokerFees;
	private BigDecimal buyerMarketFees;
	private BigDecimal buyerOrderAmount;
	private BigDecimal sellerBrokerFees;
	private BigDecimal sellerMarketFees;
	private BigDecimal sellerOrderAmount;

	public Order() {
	}

	public Order(Portfolio portfolioByBuyerPortfolioId, Portfolio portfolioBySellerPortfolioId, Security security,
			User user, Date date, int quantity, BigDecimal price, BigDecimal buyerBrokerFees,
			BigDecimal buyerMarketFees, BigDecimal buyerOrderAmount, BigDecimal sellerBrokerFees,
			BigDecimal sellerMarketFees, BigDecimal sellerOrderAmount) {
		this.portfolioByBuyerPortfolioId = portfolioByBuyerPortfolioId;
		this.portfolioBySellerPortfolioId = portfolioBySellerPortfolioId;
		this.security = security;
		this.user = user;
		this.date = date;
		this.quantity = quantity;
		this.price = price;
		this.buyerBrokerFees = buyerBrokerFees;
		this.buyerMarketFees = buyerMarketFees;
		this.buyerOrderAmount = buyerOrderAmount;
		this.sellerBrokerFees = sellerBrokerFees;
		this.sellerMarketFees = sellerMarketFees;
		this.sellerOrderAmount = sellerOrderAmount;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Portfolio getPortfolioByBuyerPortfolioId() {
		return this.portfolioByBuyerPortfolioId;
	}

	public void setPortfolioByBuyerPortfolioId(Portfolio portfolioByBuyerPortfolioId) {
		this.portfolioByBuyerPortfolioId = portfolioByBuyerPortfolioId;
	}

	public Portfolio getPortfolioBySellerPortfolioId() {
		return this.portfolioBySellerPortfolioId;
	}

	public void setPortfolioBySellerPortfolioId(Portfolio portfolioBySellerPortfolioId) {
		this.portfolioBySellerPortfolioId = portfolioBySellerPortfolioId;
	}

	public Security getSecurity() {
		return this.security;
	}

	public void setSecurity(Security security) {
		this.security = security;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getBuyerBrokerFees() {
		return this.buyerBrokerFees;
	}

	public void setBuyerBrokerFees(BigDecimal buyerBrokerFees) {
		this.buyerBrokerFees = buyerBrokerFees;
	}

	public BigDecimal getBuyerMarketFees() {
		return this.buyerMarketFees;
	}

	public void setBuyerMarketFees(BigDecimal buyerMarketFees) {
		this.buyerMarketFees = buyerMarketFees;
	}

	public BigDecimal getBuyerOrderAmount() {
		return this.buyerOrderAmount;
	}

	public void setBuyerOrderAmount(BigDecimal buyerOrderAmount) {
		this.buyerOrderAmount = buyerOrderAmount;
	}

	public BigDecimal getSellerBrokerFees() {
		return this.sellerBrokerFees;
	}

	public void setSellerBrokerFees(BigDecimal sellerBrokerFees) {
		this.sellerBrokerFees = sellerBrokerFees;
	}

	public BigDecimal getSellerMarketFees() {
		return this.sellerMarketFees;
	}

	public void setSellerMarketFees(BigDecimal sellerMarketFees) {
		this.sellerMarketFees = sellerMarketFees;
	}

	public BigDecimal getSellerOrderAmount() {
		return this.sellerOrderAmount;
	}

	public void setSellerOrderAmount(BigDecimal sellerOrderAmount) {
		this.sellerOrderAmount = sellerOrderAmount;
	}

}
