package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

/**
 * PortfolioBalance generated by hbm2java
 */
public class PortfolioBalance implements java.io.Serializable {

	private Integer id;
	private Portfolio portfolio;
	private Security security;
	private int balance;
	
	private transient StringProperty accountName = new SimpleStringProperty();
	private transient StringProperty securityName = new SimpleStringProperty();
	
	public PortfolioBalance() {
	}

	public PortfolioBalance(Portfolio portfolio, Security security, int balance) {
		this.portfolio = portfolio;
		this.security = security;
		this.balance = balance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
		accountName.setValue(portfolio.toString());
	}

	public Security getSecurity() {
		return this.security;
	}

	public void setSecurity(Security security) {
		this.security = security;
		this.securityName.setValue(security.getCode());
	}

	public int getBalance() {
		return this.balance;
	}

	public void setBalance(int balance) {
		this.balance = balance;
	}
	
	public StringProperty securityCodeProperty() {
		return securityName;
	}	
	public StringProperty balanceProperty() {
		StringProperty balanceProperty = new SimpleStringProperty();
		balanceProperty.setValue(Integer.toString(balance));
		return balanceProperty;
	}
	public IntegerProperty IdProperty() {
		IntegerProperty idProperty = new SimpleIntegerProperty();
		idProperty.setValue(id);
		return idProperty;
	}
	public StringProperty accountProperty() {
		return accountName;
	}
	
}
