package com.models;
// Generated Dec 6, 2017 5:39:32 PM by Hibernate Tools 5.2.6.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PortfolioTransaction generated by hbm2java
 */
public class PortfolioTransaction implements java.io.Serializable {

	private Integer id;
	private Portfolio portfolio;
	private Security security;
	private Date date;
	private String type;
	private String quantity;
	private BigDecimal totalQuantity;

	public PortfolioTransaction() {
	}

	public PortfolioTransaction(Portfolio portfolio, Security security, Date date, String type, String quantity,
			BigDecimal totalQuantity) {
		this.portfolio = portfolio;
		this.security = security;
		this.date = date;
		this.type = type;
		this.quantity = quantity;
		this.totalQuantity = totalQuantity;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	public Security getSecurity() {
		return this.security;
	}

	public void setSecurity(Security security) {
		this.security = security;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(BigDecimal totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

}
