package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Portfolio generated by hbm2java
 */
public class Portfolio implements java.io.Serializable {

	private Integer id;
	private Investor investor;
	private int brokerFees;
	private int marketFees;
	private Set<PortfolioTransaction> portfolioTransactions = new HashSet<PortfolioTransaction>(0);
	private Set<PortfolioBalance> portfolioBalances = new HashSet<PortfolioBalance>(0);
	private Set<Order> ordersForBuyerPortfolioId = new HashSet<Order>(0);
	private Set<Order> ordersForSellerPortfolioId = new HashSet<Order>(0);

	public Portfolio() {
	}

	public Portfolio(int brokerFees, int marketFees) {
		this.brokerFees = brokerFees;
		this.marketFees = marketFees;
	}

	public Portfolio(Investor investor, int brokerFees, int marketFees, Set<PortfolioTransaction> portfolioTransactions,
			Set<PortfolioBalance> portfolioBalances, Set<Order> ordersForBuyerPortfolioId,
			Set<Order> ordersForSellerPortfolioId) {
		this.investor = investor;
		this.brokerFees = brokerFees;
		this.marketFees = marketFees;
		this.portfolioTransactions = portfolioTransactions;
		this.portfolioBalances = portfolioBalances;
		this.ordersForBuyerPortfolioId = ordersForBuyerPortfolioId;
		this.ordersForSellerPortfolioId = ordersForSellerPortfolioId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Investor getInvestor() {
		return this.investor;
	}

	public void setInvestor(Investor investor) {
		this.investor = investor;
	}

	public int getBrokerFees() {
		return this.brokerFees;
	}

	public void setBrokerFees(int brokerFees) {
		this.brokerFees = brokerFees;
	}

	public int getMarketFees() {
		return this.marketFees;
	}

	public void setMarketFees(int marketFees) {
		this.marketFees = marketFees;
	}

	public Set<PortfolioTransaction> getPortfolioTransactions() {
		return this.portfolioTransactions;
	}

	public void setPortfolioTransactions(Set<PortfolioTransaction> portfolioTransactions) {
		this.portfolioTransactions = portfolioTransactions;
	}

	public Set<PortfolioBalance> getPortfolioBalances() {
		return this.portfolioBalances;
	}

	public void setPortfolioBalances(Set<PortfolioBalance> portfolioBalances) {
		this.portfolioBalances = portfolioBalances;
	}

	public Set<Order> getOrdersForBuyerPortfolioId() {
		return this.ordersForBuyerPortfolioId;
	}

	public void setOrdersForBuyerPortfolioId(Set<Order> ordersForBuyerPortfolioId) {
		this.ordersForBuyerPortfolioId = ordersForBuyerPortfolioId;
	}

	public Set<Order> getOrdersForSellerPortfolioId() {
		return this.ordersForSellerPortfolioId;
	}

	public void setOrdersForSellerPortfolioId(Set<Order> ordersForSellerPortfolioId) {
		this.ordersForSellerPortfolioId = ordersForSellerPortfolioId;
	}

	@Override
	public String toString() {
		return investor.getName();
	}
}
