package com.models;
// Generated Dec 9, 2017 10:15:37 AM by Hibernate Tools 5.2.6.Final

/**
 * PortfolioBalance generated by hbm2java
 */
public class PortfolioBalance implements java.io.Serializable {

	private Integer id;
	private Portfolio portfolio;
	private Security security;
	private int balance;

	public PortfolioBalance() {
	}

	public PortfolioBalance(Portfolio portfolio, Security security, int balance) {
		this.portfolio = portfolio;
		this.security = security;
		this.balance = balance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Portfolio getPortfolio() {
		return this.portfolio;
	}

	public void setPortfolio(Portfolio portfolio) {
		this.portfolio = portfolio;
	}

	public Security getSecurity() {
		return this.security;
	}

	public void setSecurity(Security security) {
		this.security = security;
	}

	public int getBalance() {
		return this.balance;
	}

	public void setBalance(int balance) {
		this.balance = balance;
	}

}
