package com.models;
// Generated Dec 9, 2017 10:15:37 AM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * RoleType generated by hbm2java
 */
public class RoleType implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Set<User> users = new HashSet<User>(0);

	public RoleType() {
	}

	public RoleType(String roleName) {
		this.roleName = roleName;
	}

	public RoleType(String roleName, Set<User> users) {
		this.roleName = roleName;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
