package com.models;
<<<<<<< HEAD

import javafx.beans.property.*;

public class Security {
    //Declare Employees Table Columns
    private IntegerProperty id;
    private StringProperty name;
    private StringProperty code;
    private Exchange exchange;
    //Constructor
    public Security() {
        this.id = new SimpleIntegerProperty();
        this.name = new SimpleStringProperty();
        this.code = new SimpleStringProperty();
        this.exchange = new Exchange();
    }

    //employee_id
    public int getId() {
        return id.get();
    }

    public void setId(int Id){
        this.id.set(Id);
    }

    public IntegerProperty IdProperty(){
        return id;
    }

    //first_name
    public String getName () {
        return name.get();
    }

    public void setName(String Name){
        this.name.set(Name);
    }

    public StringProperty NameProperty() {
        return name;
    }
    public String getCode () {
        return code.get();
    }

    public void setCode(String code){
        this.code.set(code);
    }

    public StringProperty CodeProperty() {
        return code;
    }

	public Exchange getExchange() {
		return exchange;
	}
	public StringProperty getExchangeName() {
		StringProperty exchangeName = new SimpleStringProperty();
		exchangeName.set(exchange.getShortName());
		return exchangeName;
	}

	public void setExchange(Exchange exchange) {
		this.exchange = exchange;
	}

    //last_name
    
=======
// Generated Dec 6, 2017 5:39:32 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Security generated by hbm2java
 */
public class Security implements java.io.Serializable {

	private Integer id;
	private Exchange exchange;
	private String name;
	private String code;
	private Set<PortfolioTransaction> portfolioTransactions = new HashSet<PortfolioTransaction>(0);
	private Set<PortfolioBalance> portfolioBalances = new HashSet<PortfolioBalance>(0);
	private Set<Order> orders = new HashSet<Order>(0);
	private Set<SecurityPrice> securityPrices = new HashSet<SecurityPrice>(0);

	public Security() {
	}

	public Security(Exchange exchange, String name, String code) {
		this.exchange = exchange;
		this.name = name;
		this.code = code;
	}

	public Security(Exchange exchange, String name, String code, Set<PortfolioTransaction> portfolioTransactions,
			Set<PortfolioBalance> portfolioBalances, Set<Order> orders, Set<SecurityPrice> securityPrices) {
		this.exchange = exchange;
		this.name = name;
		this.code = code;
		this.portfolioTransactions = portfolioTransactions;
		this.portfolioBalances = portfolioBalances;
		this.orders = orders;
		this.securityPrices = securityPrices;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Exchange getExchange() {
		return this.exchange;
	}

	public void setExchange(Exchange exchange) {
		this.exchange = exchange;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Set<PortfolioTransaction> getPortfolioTransactions() {
		return this.portfolioTransactions;
	}

	public void setPortfolioTransactions(Set<PortfolioTransaction> portfolioTransactions) {
		this.portfolioTransactions = portfolioTransactions;
	}

	public Set<PortfolioBalance> getPortfolioBalances() {
		return this.portfolioBalances;
	}

	public void setPortfolioBalances(Set<PortfolioBalance> portfolioBalances) {
		this.portfolioBalances = portfolioBalances;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

	public Set<SecurityPrice> getSecurityPrices() {
		return this.securityPrices;
	}

	public void setSecurityPrices(Set<SecurityPrice> securityPrices) {
		this.securityPrices = securityPrices;
	}

>>>>>>> branch 'Hibernate' of https://github.com/xtrememind/TradeSys/
}
