package com.models;
// Generated Dec 10, 2017 7:29:30 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private RoleType roleType;
	private String name;
	private String userName;
	private String passWord;
	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}

	public User(RoleType roleType, String name, String userName, String passWord) {
		this.roleType = roleType;
		this.name = name;
		this.userName = userName;
		this.passWord = passWord;
	}

	public User(RoleType roleType, String name, String userName, String passWord, Set<Order> orders) {
		this.roleType = roleType;
		this.name = name;
		this.userName = userName;
		this.passWord = passWord;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
