package com.models;
<<<<<<< HEAD

import javafx.beans.property.*;

public class User {
    //Declare Employees Table Columns
    private IntegerProperty id;
    private StringProperty name;
    private StringProperty userName;
    private StringProperty passWord;
    private Role role;

    //Constructor
    public User() {
        this.id = new SimpleIntegerProperty();
        this.name = new SimpleStringProperty();
        this.userName = new SimpleStringProperty();
        this.passWord = new SimpleStringProperty();
        this.role = new Role(0,"Admin");

    }

    //employee_id
    public int getId() {
        return id.get();
    }

    public void setId(int Id){
        this.id.set(Id);
    }

    public IntegerProperty IdProperty(){
        return id;
    }

    //first_name
    public String getName () {
        return name.get();
    }

    public void setName(String Name){
        this.name.set(Name);
    }

    public StringProperty NameProperty() {
        return name;
    }
    public String getUserName () {
        return userName.get();
    }

    public void setUserName(String code){
        this.userName.set(code);
    }

    public StringProperty UserNameProperty() {
        return userName;
    }

    public String getPassWord () {
        return passWord.get();
    }

    public void setPassWord(String code){
        this.passWord.set(code);
    }

    public StringProperty PassWordProperty() {
        return passWord;
    }
    public Role getRole() {
		return role;
	}
	public StringProperty getRoleName() {
		StringProperty roleName = new SimpleStringProperty();
		roleName.set(role.getRoleName());
		return roleName;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	
    //last_name
    
=======
// Generated Dec 6, 2017 5:39:32 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private RoleType roleType;
	private String name;
	private String userName;
	private String passWord;
	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}

	public User(RoleType roleType, String name, String userName, String passWord) {
		this.roleType = roleType;
		this.name = name;
		this.userName = userName;
		this.passWord = passWord;
	}

	public User(RoleType roleType, String name, String userName, String passWord, Set<Order> orders) {
		this.roleType = roleType;
		this.name = name;
		this.userName = userName;
		this.passWord = passWord;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RoleType getRoleType() {
		return this.roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassWord() {
		return this.passWord;
	}

	public void setPassWord(String passWord) {
		this.passWord = passWord;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

>>>>>>> branch 'Hibernate' of https://github.com/xtrememind/TradeSys/
}
